### ISSUE TITLE
Executable

### ISSUE THREAD

**Issue by matheusjardimb** [DoubleYo/iOS-2-Androit-Assets#1]
The idea of this project looks awesome! But I wouldn't install the setup you're asking just to get files renamed. 

Have you ever tought about distributing executables?

**Comment by ghost** [comment]
Hi, I already think of distributing executable but you need some other soft like imagemagik in order to get it work. I also don't distributing executable beacause of cross platforme problematic.

If the README file is not clear enougth let me know where.
